networks:
  interpre_network:
    external: true

name: interpre-docker

services:
  interpre-app:
    image: nginx:latest
    ports:
      - "8811:80"
    volumes:
      - ./:/var/www/html
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - interpre_network
    restart: "no"

  php:
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "9011:9000"
    networks:
      - interpre_network
    restart: "no"
